# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-feed
# spec:
#   selector:
#     app: backend-feed
#   ports:
#     - protocol: TCP
#       port: 8080
#       targetPort: 8080
apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: backend-feed
