apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    run: udagram-frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 80
      