# apiVersion: apps/v1

# kind: Deployment

# metadata:

#   name: reverseproxy

#   labels:

#     app: reverseproxy

# spec:

#   replicas: 1

#   selector:

#     matchLabels:

#       app: reverseproxy

#   template:

#     metadata:

#       labels:

#         app: reverseproxy

#     spec:

#       containers:

#       - name: reverseproxy

#         image: kirubelfikru/reverseproxy:v1

#         ports:

#         - containerPort: 8080



apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  selector:
    matchLabels:
      service: reverseproxy
  replicas: 1
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: kirubelfikru/reverseproxy:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
      restartPolicy: Always       