apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-user
  name: backend-user
spec:
  selector:
    matchLabels:
      app: backend-user
  replicas: 2
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: kirubelfikru/udagram-api-user:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: "2092Mi"
          requests:
            cpu: 500m
            memory: "1024Mi"
        envFrom:
        - configMapRef:
            name: udagram-env
        - secretRef:
            name: udagramdb-env
      restartPolicy: Always